name: Retrieve system network information
description: Retrieve information about the system's networking using "ipconfig"
metadata:
  isv: 1
  tactic: TA0007
  tid: T1016
  x_vectr_id: 67d05a60-d0aa-4b9c-87cc-d85a5a19922c
  groups:
  - APT41
platforms:
- windows
guidance:
- CMD> ipconfig /all
block:
- null
detect:
- Suspicious process execution/behavior is detected by endpoint security tool or triggers
  alert in SIEM based on telemetry
logs:
- edr:telemetry
- process_create
controls:
- Endpoint Protection
- SIEM
